### ISSUE TITLE
Add an argument to change the base dn to be searched

### ISSUE THREAD

**Issue by executionByFork** [yaap7/ldapsearch-ad#17]
I like this tool. It is simple to use for LDAP querying and the outputs are easy to read/understand. However, it seems this cannot query everything. There is no command line argument to change the base dn that gets queried.

For example, this LDAP query using ldapsearch-ad returns nothing:
`ldapsearch-ad -l <DOMAIN_CONTROLLER> -d <DOMAIN> -u <USERNAME> -p '<PASSWORD>' -t search -s '(objectclass=pKIEnrollmentService)'`

However, using ldapsearch (default installed on kali) works. The following command pulls certificate authority AD objects:
`ldapsearch -D '<FULL_USER_DN>' -w '<PASSWORD>' -H 'ldap://<DOMAIN_CONTROLLER>' -b 'CN=Configuration,DC=corp,DC=local' '(objectclass=pKIEnrollmentService)'`
This is because the ldapsearch tool has an argument (`-b`) to set the base dn to query, whereas ldapsearch-ad does not.

It would be very helpful to expose a command line argument that allows a user to set the base dn as needed. The ldapsearch tool requires the full DN to be specified for auth which is tedious, and it does not accept NTLM hashes. I'd rather use ldapsearch-ad for any of my ldap querying needs, but it needs the flexibility to set the base

**Comment by yaap7** [comment]
Thanks for this precious feedback.
Obviously, I was not aware about different DN when I first code this tool.
You're right about this need and I will try to add this functionnality in a near future.
